stages:
- name: Deployment
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: django
      pushRemote: true
      registry: 127.0.0.1:34489
timeout: 60
notification: {}
