stages:
- name: Deployment
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: django
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
