name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: docker:19.03.1

    steps:
    - uses: actions/checkout@v2
    - name: docker:19.03.1-dind
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
